### ISSUE TITLE
Add component level alerts

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2176]
There might be situations where Weblate can detect something wrong with the repository setup and suggest a fix. These might be expensive checks to be executed nightly or triggered normally during operation.

Things which should be checked nightly:

* [x] Missing webhook setup for known supported repositories (GitHub, GitLab, BitBucket)
* [x] Project is near to it's billing limits
* [ ] Too many failing checks
* [x] Too many not merged commits in the Weblate repository
* [x] Push URL not configured (maybe)

Thinks which would trigger on the fly:

* [x] Parse errors in some of the files (see also #1112)
* [x] Merge failure
* [x] Duplicate units found (see also #1112)
* [x] Duplicate languages found
* [x] Update remote fails (currently this is only logged)
* [x] Base file is set, but adding languages is not allowed (see #2285)

PS: Maybe warnings is not the best name, better suggestions welcome.

**Comment by nijel** [comment]
Further things:

* Push URL not configured
* Extra commits in the Weblate repository

**Comment by nijel** [comment]
* Update remote fails (currently this is only logged)

**Comment by nijel** [comment]
* Base file is set, but adding languages is not allowed

**Comment by nijel** [comment]
Also the warnings should be triggered immediately after creating a component to bring user to page with warnings after creating it.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
