### ISSUE TITLE
Remove usage of Django admin interface

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2363]
**Is your feature request related to a problem? Please describe.**
Having both Django admin inteface and Weblate itself is confusing and using generic Django admin interface leads to several problems.

**Describe the solution you'd like**
All should be handled directly in Weblate.

**Describe alternatives you've considered**
More customization of Django admin could achieve better behavior, but still some things are hard to address (see https://code.djangoproject.com/ticket/10919).

**Additional context**
Things currently done *only* in the Django admin, but should be possible from Weblate:

* [x] Performance report
* [x] Repositories status
* [x] SSH keys management (replaced by https://github.com/WeblateOrg/weblate/issues/2459)
* [x] Global user and group management, automatic group assignments (related to https://github.com/WeblateOrg/weblate/issues/2246 and https://github.com/WeblateOrg/weblate/issues/2493 and https://github.com/WeblateOrg/weblate/issues/2126 and https://github.com/WeblateOrg/weblate/issues/2127)
* [x] Whiteboard
* [ ] Component lists (see https://github.com/WeblateOrg/weblate/issues/1370 and https://github.com/WeblateOrg/weblate/issues/11549 and https://github.com/WeblateOrg/weblate/issues/7181)
* [x] Deletion (see https://github.com/WeblateOrg/weblate/issues/2221)
* [x] Adding languages (see https://github.com/WeblateOrg/weblate/issues/2491)

New features in the interface:

* [x] Sending test mail (see https://github.com/WeblateOrg/weblate/issues/2517)

Things which might stay relying on Django Admin forever:

* Audit logs
* Social auth details
* Billing management

**Comment by reloxx13** [comment]
i cannot see deleted/disabled users in weblate ui are not shown which i see in the admin interface.    
i would also prefer a cleaner user list like the table in djangi admin ui and not so blown up.

**Comment by nijel** [comment]
As you can see, this issue is still in progress...

**Comment by nijel** [comment]
The only remaining bit here are the component lists which need more than just interface changes, see https://github.com/WeblateOrg/weblate/issues/12160. Let's close this issue as all other things have been addressed and this is no longer useful.
