### ISSUE TITLE
Improved notifications system

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2542]
**Is your feature request related to a problem? Please describe.**
Current notification system really doesn't work well for many situations, there are several separate issues already in the tracker, but this is to track overall desired state.

**Describe the solution you'd like**

In general:

* [x] Add support for digest notifications https://github.com/WeblateOrg/weblate/issues/1046
* [x] Subscription to events per project, not globally
* [x] One click unsubscribe from email

The notifications should cover following areas:

* [x] Source string change https://github.com/WeblateOrg/weblate/issues/1675
* [x] Pending suggestions (batch) https://github.com/WeblateOrg/weblate/issues/1349
* [x] Component alerts https://github.com/WeblateOrg/weblate/issues/1112
* [x] Project messages/news https://github.com/WeblateOrg/weblate/issues/585
* [x] User edited string has been changed or commented https://github.com/WeblateOrg/weblate/issues/2579
* [x] New component within a project https://github.com/WeblateOrg/weblate/issues/1956
* [x] New language added https://github.com/WeblateOrg/weblate/issues/567
* [x] Translation reminders (batch) https://github.com/WeblateOrg/weblate/issues/1352
* [x] Remove explicit `mail_admins`, everything should go through subscriptions

**Comment by ldmpub** [comment]
Hi Michal,

Can you confirm in which weblate version the recently closed #730 request will be included and if there is any documentation on how to use this new feature? (I've found nothing related to the watch notifications in https://docs.weblate.org).

Thanks,

**Comment by nijel** [comment]
It will be part of the 3.6 release, see the milestone set on the issue. The docs still needs some improvements to cover new notifications in full detail...

**Comment by ldmpub** [comment]
Thanks for your answer.
I need the documentation because I didn't see any change in 3.6-dev hosted on hosted.weblate.org.

**Comment by nijel** [comment]
It's not yet deployed on hosted.weblate.org, so it's expected that you don't see any change there ;-).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
